name: unit-test
run-name: ${{ github.actor }} run UnitTests
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Test with unittest
        run: |
          python -m unittest discover -s ./src/test  -p 'test_*.py'