name: unit-test
run-name: ${{ github.actor }} run UnitTests
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Test with pytest
        run: |
           python -m unittest discover src/test